version: '3.4'

volumes:
  mongodb_data:
  mysql_data:
  rabbitmq_data:
  logs:

networks:
  marketcloud-network:

services:
  #############################################################
  #                 RABBITMQ CONFIG BLOCK                     #
  #############################################################
  rabbitmq:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - marketcloud-network
    hostname: marketcloud-rabbitmq-1
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"



  #############################################################
  #                  MONGODB CONFIG BLOCK                     #
  #############################################################
  mongodb:
    restart: unless-stopped
    hostname: marketcloud-mongodb-1
    image: mongo
    networks:
      - marketcloud-network
    expose:
      - "27017"
    volumes:
      - 'mongodb_data:/data/db'




  #############################################################
  #                 MYSQL CONFIG BLOCK                        #
  #############################################################
  mysql:
    restart: unless-stopped
    hostname: marketcloud-mysql-1
    image: mysql:5.7
    networks:
      - marketcloud-network
    environment:
      MYSQL_DATABASE: 'marketcloud'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'marketcloud-mysql-user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'marketcloud-mysql-password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql-root-password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql



  #############################################################
  #                 API CONFIG BLOCK                        #
  #############################################################
  api:
    restart: unless-stopped
      build: 
        context: ../marketcloud-api
        dockerfile: Dockerfile
      ports:
      - 5000:5000
      env_file: .env
      depends_on:
        - mongodb
        - mysql
        - rabbitmq



    #############################################################
  #                 ADMIN UI CONFIG BLOCK                      #
  #############################################################
  website:
    restart: unless-stopped
      build: 
        context: ../marketcloud-website
        dockerfile: Dockerfile
      ports:
      - 8000:8000
      env_file: .env
      depends_on:
        - mongodb
        - mysql
        - rabbitmq
        - api

    #############################################################
  #                 MAILER SERVICE CONFIG BLOCK                #
  #############################################################
  mailer-service:
    restart: unless-stopped
      build: 
        context: ../marketcloud-mailer
        dockerfile: Dockerfile
      env_file: .env
      depends_on:
        - mongodb
        - mysql
        - rabbitmq
        - api

    #############################################################
  #                 WEBHOOKS CONFIG BLOCK                      #
  #############################################################
  wevhooks-service:
    restart: unless-stopped
      build: 
        context: ../marketcloud-webhook-service
        dockerfile: Dockerfile
      env_file: .env
      depends_on:
        - mongodb
        - mysql
        - rabbitmq
        - api